server:
  port: 8081
  servlet:
    context-path:

spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      minimum-idle: 3
      max-lifetime: 120000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.137.190:3306/virus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: virus
    password: L2jniEckBkMTKjDH

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false